<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>7f0f6e87-001e-4909-aa7f-6c354586282a</testSuiteGuid>
   <testCaseLink>
      <guid>c6ca619a-ce33-40aa-840e-506a53218acf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User Login Test Cases/User Login With Invalid Credentials</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d2161b3e-07d8-4216-bde2-0139bba5ce4b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login/Development/Internal Data Files/ID - Invalid Login User Credentials Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d2161b3e-07d8-4216-bde2-0139bba5ce4b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>6c50f103-6484-4ecd-872a-26c5e42be934</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d2161b3e-07d8-4216-bde2-0139bba5ce4b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>21c2e800-227e-4518-8ac6-65da3ed03ff8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>829891ad-a308-4ef8-8701-65e9f5ae9413</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User Login Test Cases/User Login With Null Credentials</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2be92d33-5dea-4f7a-aed7-475d3b4456b4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login/Development/Internal Data Files/ID - Null Login User Credentials</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>2be92d33-5dea-4f7a-aed7-475d3b4456b4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>76e14032-0224-4c96-97eb-8a757d8c2d61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2be92d33-5dea-4f7a-aed7-475d3b4456b4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>043e6f2d-257b-49fb-99ae-b14018da1d52</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d268846-209b-411e-bfa7-d33a7eee51b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User Login Test Cases/User Login With Valid Credentials</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b82aa90f-db5b-42a2-bd97-cf9a3c5b8392</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login/Development/Internal Data Files/ID - Valid Login User Credentials Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>b82aa90f-db5b-42a2-bd97-cf9a3c5b8392</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>44e467b7-ffdd-4c28-9e7a-01d2b85477b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b82aa90f-db5b-42a2-bd97-cf9a3c5b8392</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>d98e364e-8759-4f81-920e-ae0437ae38e5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
