<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Text And Or Link - Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0aa1434e-6dad-45cd-b757-fa4c2a46481f</testSuiteGuid>
   <testCaseLink>
      <guid>d1a4dcab-f5fa-41fd-834c-f4a8d1f9095b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Posts Lab/Text And Or Link/Test Case 1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>66937bb5-e3f7-4342-852a-13c997be8a40</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Posts/Internal Data Files/Text And Or Link/Text And Or Link - Internal Test Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>66937bb5-e3f7-4342-852a-13c997be8a40</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>9f36ac72-3c8c-4d2e-9455-0f27ef4ce85f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>66937bb5-e3f7-4342-852a-13c997be8a40</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>a3e6d966-d87d-4df0-b0bb-c891e2b964f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>66937bb5-e3f7-4342-852a-13c997be8a40</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>enterTextAndOrLink</value>
         <variableId>9f182089-78f0-445a-a4eb-6a50b409bbfa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac10a206-a94a-4f7e-a47e-f6f11bc052ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Posts Lab/Text And Or Link/Test Case 2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5adcbb8a-56d4-498d-aab7-66caef557000</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>222a306b-95ef-48d1-8b3d-d7e7ef1c84e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8e07fba-3e5f-4f25-90cd-6911579680c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f1676f87-ba54-47b1-873c-6029e5fc834e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Posts Lab/Text And Or Link/Test Case 3</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d55b6b7-8da9-436b-80bc-ebddada900b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8eeb81d2-0e00-422d-8073-e756f16ad828</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b5baeb9-c5a3-4b3f-ac14-5a8b8cb3b314</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>703e1678-54e7-459d-bb9b-5c3a628f16b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Posts Lab/Text And Or Link/Test Case 4</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22e0a052-fd07-4f0d-b492-e26744651c78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f1333ad-791c-44ad-beda-234f84a71fab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc7e32db-242b-47cd-b0ee-e79d715f13b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5be05490-94b2-493b-85c9-c5bfb01a0dae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Posts Lab/Text And Or Link/Test Case 5</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04d7a3b8-a9ef-4190-b419-dbfa49eedfdc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dac2e56f-6532-4d32-9f1f-51d05d771fc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c41ceaa-c082-434b-9ed9-b6c94c01fc02</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f98a7694-9474-4153-a57a-f926975c8bfa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Posts Lab/Text And Or Link/Test Case 6</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21988858-871e-4c6b-928c-bd328315a82a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9366018c-ef1c-47cf-9f09-6f300fca609d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d605b8d-4ed7-4f4c-8ea0-090408e380c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b59af865-11e6-44ab-a324-6c3505e9de99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Posts Lab/Text And Or Link/Test Case 7</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e03b7a4c-e516-466f-b434-8f96b11e21c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29d0e104-5999-4660-a45d-31c14e3a833f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3945e8ac-4ea9-4476-8bd9-a993e7304801</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf0e111d-c4ed-4231-a2eb-29ea4d9fd739</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Posts Lab/Text And Or Link/Test Case 8</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7a0d17e-60be-4ac7-bb45-4915b43f9d68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e7c5e8a-b4c4-4289-b2bd-a7d97c8b89d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07a12ae0-1191-4f0a-a54f-5458cd2919d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2e6b43cd-ac07-44f0-b4de-3cba4d9515ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Posts Lab/Text And Or Link/Adding A Facebook Profile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7daad1ad-67a4-4609-a0a9-4fcb04ca95ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8642412e-8355-434c-af32-4920d53e02c8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
